name: 'Test RAG and CoT for all models'

on:
  workflow_dispatch:


jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - name: 'set up Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
         
      - name: 'set up Python dependencies'
        shell: bash
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt
          
      # - name: 'set up Microsoft Phi-3 Mini 4k LLM from HuggingFace'
      #   shell: bash
      #   run: |
      #     pip install huggingface-hub[cli]
      #     huggingface-cli download microsoft/Phi-3-mini-4k-instruct-onnx --include cpu_and_mobile/cpu-int4-rtn-block-32-acc-level-4/* --local-dir ${{ github.workspace }}/infrastructure/foundation_model

      - name: 'test RAG and CoT for all models'
        shell: bash  
        run: |
          pytest -k test_04_malicious_prompts_rag_and_cot -s --disable-warnings

