name: 'LLM Prompt Testing (LLM, no RAG)'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683    

    - name: 'set up git LFS'
      run: git lfs install

    - name: 'set up Python'
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: 'set up Python dependencies'
      run: |
        pip install -r ${{ github.workspace }}/requirements.txt  

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-lightboker-llmsecopsresearch
            
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 'set up Microsoft Phi-3 Mini 4k LLM from HuggingFace'
      run: |
        pip install huggingface-hub[cli]
        huggingface-cli download microsoft/Phi-3-mini-4k-instruct-onnx --include cpu_and_mobile/cpu-int4-rtn-block-32-acc-level-4/* --local-dir ${{ github.workspace }}/src/llm

    - name: 'set up garak'
      run: |
        pip install garak
      
    - name: 'run REST API, health check, and garak tests'
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        nohup python -m src.api.controller &
        sleep 60

        curl -i http://localhost:9999/

        echo "Making API request..."
        curl -X POST -i http://localhost:9999/api/conversations \
            -d '{ "prompt": "describe a random planet in our solar system in 10 words or less" }' \
            -H "Content-Type: application/json" || exit 1

        garak -v \
          --config ${{ github.workspace }}/src/tools/garak.config.yml \
          --generator_option_file ${{ github.workspace }}/src/tools/garak.rest.llm.json \
          --model_type=rest \
          --parallel_attempts 32

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: 'garak_report'
        path: /home/runner/.local/share/garak/garak_runs/garak.*.html