name: 'Test #4 | RAG + CoT | microsoft/Phi-3-mini-4k-instruct'
on:
  workflow_dispatch:

jobs:
  test-all-ranges:
    strategy:
      matrix:
        include:
          - offset: 0
            range: "1-20"
          - offset: 20
            range: "21-40"
          - offset: 40
            range: "41-60"
          - offset: 60
            range: "61-80"
          - offset: 80
            range: "81-100"
      fail-fast: false
    uses: ./.github/workflows/test_04_malicious_prompts_rag_and_cot_microsoft_phi_3_mini4k_instruct.base.yml
    with:
      batch_offset: ${{ matrix.offset }}
      range_name: ${{ matrix.range }}
      batch_size: 2