name: '#4 (81-100) | RAG + CoT | microsoft/Phi-3-mini-4k-instruct'
on:
  workflow_dispatch:
  schedule:
    # Workflow 5 - Starts at hours: 4, 9, 14, 19 (every 5th hour starting from 4 AM)
    - cron: '0 4-19/5 * * *'

jobs:
  test-prompts-81-100:
    uses: ./.github/workflows/test_04_malicious_prompts_rag_and_cot_microsoft_phi_3_mini4k_instruct.base.yml
    with:
      batch_offset: 80
      range_name: "81-100"
      batch_size: 2