name: 'Reusable Test #4 | RAG + CoT | meta-llama/Llama-3.2-3B-Instruct'
on:
  workflow_call:
    inputs:
      batch_offset:
        description: 'Starting prompt index offset'
        required: true
        type: number
      range_name:
        description: 'Human readable range name (e.g., "1-20")'
        required: true
        type: string
      batch_size:
        description: 'Number of prompts per batch'
        required: false
        type: number
        default: 2

jobs:
  test:
    uses: ./.github/workflows/test_04.abstract_base.yml
    with:
      batch_offset: ${{ inputs.batch_offset }}
      range_name: ${{ inputs.range_name }}
      batch_size: ${{ inputs.batch_size }}
      test_file_path: tests/integration/test_04_malicious_prompts_rag_and_cot_meta_llama_3_2_3b_instruct.py
      model_display_name: meta-llama/Llama-3.2-3B-Instruct