name: 'Test #4 | RAG + CoT | apple/OpenELM-3B-Instruct'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - name: 'set up Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
         
      - name: 'set up Python dependencies'
        shell: bash
        run: pip install -r ${{ github.workspace }}/requirements.txt
          
      - name: 'run text generation tests'
        shell: bash
        working-directory: tests/integration
        env:
          INJECTION_DATA_DIR: "${{ github.workspace }}/tests/security/tests/results/01_garak_no_guidelines"
        run: pytest test_04_malicious_prompts_rag_and_cot_apple_openelm_3b_instruct.py -s --disable-warnings

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "42450907+lightbroker@users.noreply.github.com"
          git config --local user.name "Adam Wilson"
          git add .
          git commit -m "Auto-generated files from workflow [skip ci]"
          git push