name: 'Reusable Test #2 | CoT | Malicious'
on:
  workflow_call:
    inputs:
      batch_offset:
        description: 'Starting prompt index offset'
        required: true
        type: number
      range_name:
        description: 'Human readable range name (e.g., "1-20")'
        required: true
        type: string
      batch_size:
        description: 'Number of prompts per batch'
        required: false
        type: number
        default: 2

jobs:
  test:
    uses: ./.github/workflows/tests.abstract_base.yml
    with:
      batch_offset: ${{ inputs.batch_offset }}
      range_name: ${{ inputs.range_name }}
      batch_size: ${{ inputs.batch_size }}
      test_file_path: tests/integration/test_02_malicious_prompts_cot.py
      model_display_name: microsoft/Phi-3-mini-4k-instruct-onnx